services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=customers
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
volumes:
  db-data:
